# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'shlee'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'google-ID'

menu: 
  - name: Featured Projects
    submenu:
      - name: IT tech(Programming, Network, etc)
        link: /projects/microbam
      - name: Life Posting
        link: /projects/ourlegacy
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/OYSSanghyuk
      - name: LinkedIn
        icon: linkedin-square
        link: 
      - name: Twitter
        icon: twitter
        link: https://twitter.com/koint
    
